import { spawn, execFileSync, type ChildProcess } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { createServer as createNetServer, connect } from "node:net";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import type { AddressInfo } from "node:net";
import { afterEach, describe, expect, it } from "vitest";

import { createGateway } from "../src/gateway.js";
import { OmnigentRuntime } from "../src/omnigent-runtime.js";
import type { RuntimeSessionRequest } from "../src/runtime.js";

const integration =
  process.env.RUN_OMNIGENT_INTEGRATION === "1" ? describe : describe.skip;
const repositoryRoot = resolve(import.meta.dirname, "../../..");
const compat = JSON.parse(
  readFileSync(
    join(repositoryRoot, "config/omnigent-test-compat.json"),
    "utf8",
  ),
) as { version: string };
const liveGateways: ReturnType<typeof createGateway>[] = [];

afterEach(async () => {
  await Promise.all(liveGateways.splice(0).map(closeServer));
});

integration("real Omnigent with deterministic ACP", () => {
  it("completes a request-scoped MCP tool loop through the gateway", async () => {
    const result = await withIsolatedOmnigent(async (harness) => {
      return exerciseToolLoop(harness);
    });

    expect(result.value.text).toContain(result.value.nonce);
    expect(result.value.completed).toBe(true);
    expect(result.value.transcript).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ kind: "acp.request", method: "initialize" }),
        expect.objectContaining({
          kind: "acp.request",
          method: "session/new",
        }),
        expect.objectContaining({
          kind: "acp.request",
          method: "session/prompt",
        }),
        expect.objectContaining({ kind: "mcp.request", method: "tools/list" }),
        expect.objectContaining({
          kind: "mcp.request",
          method: "tools/call",
          params: { name: "get_test_nonce", arguments: {} },
        }),
      ]),
    );
    const resultEvent = result.value.transcript.find(
      (event) => event["kind"] === "agent.tool_result",
    );
    expect(JSON.stringify(resultEvent)).toContain(result.value.nonce);
    expect(existsSync(result.root)).toBe(false);
    await expectPortClosed(result.serverPort);
    for (const processGroupId of result.processGroupIds) {
      expect(processGroupExists(processGroupId)).toBe(false);
    }
    expect(findProcessesReferencing(result.root)).toEqual([]);
    expect(result.operatorCanaryAfter).toEqual(result.operatorCanaryBefore);
  }, 120_000);

  it("cleans up isolated processes and files after a post-start failure", async () => {
    let root = "";
    let serverPort = 0;
    let reachedMcpToolCall = false;
    let activePids: number[] = [];
    let processGroupIds: number[] = [];
    let operatorCanaryBefore: Record<string, string> = {};
    await expect(
      withIsolatedOmnigent(async (harness) => {
        root = harness.root;
        serverPort = harness.serverPort;
        processGroupIds = [...harness.processGroupIds];
        operatorCanaryBefore = harness.operatorCanaryBefore;
        await exerciseToolLoop(harness, {
          onActionRequired: () => {
            reachedMcpToolCall = true;
            activePids = harness.activePids();
            throw new Error("deliberate integration cleanup probe");
          },
        });
      }),
    ).rejects.toThrow("deliberate integration cleanup probe");

    expect(root).not.toBe("");
    expect(reachedMcpToolCall).toBe(true);
    expect(activePids.length).toBeGreaterThanOrEqual(4);
    expect(existsSync(root)).toBe(false);
    await expectPortClosed(serverPort);
    for (const processGroupId of processGroupIds) {
      expect(processGroupExists(processGroupId)).toBe(false);
    }
    expect(findProcessesReferencing(root)).toEqual([]);
    expect(snapshotOperatorCanaries()).toEqual(operatorCanaryBefore);
  }, 90_000);
});

// Milestone 0.5 of docs/plan/open-responses-vertical-slice.md. Disposable: this
// answers the go/no-go question for the Open Responses pivot and is not a
// component. It talks to Omnigent directly rather than through the gateway,
// because the properties under test belong to the provider — today's gateway
// still aborts the upstream stream when its client disconnects, which is the
// exact coupling the new backend must remove.
integration("Omnigent ownership spike (Milestone 0.5)", () => {
  const spikeTools = [
    {
      name: "get_test_nonce",
      description: "Return an unpredictable nonce generated by the application",
      inputSchema: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
    {
      name: "confirm_test_nonce",
      description: "Acknowledge a nonce previously produced by the application",
      inputSchema: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  ];

  it("retains one run across a detached stream, two calls, and a snapshot", async () => {
    const result = await withIsolatedOmnigent(
      async (harness) => {
        const runtime = new OmnigentRuntime({
          baseUrl: harness.serverUrl,
          workspace: harness.workspace,
          launchTimeoutMs: 30_000,
          pollIntervalMs: 100,
        });
        const providerSessionId = await runtime.createSession({
          appId: "ownership-spike",
          origin: "https://integration.example",
          toolHash: "spike",
          approvedToolNames: spikeTools.map((item) => item.name),
        });
        const base = `${harness.serverUrl}/v1/sessions/${encodeURIComponent(providerSessionId)}`;
        const internal = { Origin: "omnigent://internal" };

        const openStream = async (): Promise<ReadableStream<Uint8Array>> => {
          const response = await fetch(`${base}/stream`, {
            headers: { ...internal, Accept: "text/event-stream" },
          });
          expect(response.status).toBe(200);
          expect(response.body).not.toBeNull();
          return response.body!;
        };
        const post = async (body: unknown): Promise<number> => {
          const response = await fetch(`${base}/events`, {
            method: "POST",
            headers: { ...internal, "Content-Type": "application/json" },
            body: JSON.stringify(body),
          });
          await response.text();
          return response.status;
        };
        const snapshot = async (): Promise<Record<string, unknown>> => {
          const response = await fetch(base, { headers: internal });
          expect(response.status).toBe(200);
          return (await response.json()) as Record<string, unknown>;
        };
        // Reads until one application call is observed, then abandons the
        // stream. Returning from inside `for await` cancels the underlying
        // reader, which is the deliberate mid-run detach under test.
        const readUntilCall = async (
          stream: ReadableStream<Uint8Array>,
        ): Promise<{
          callId: string;
          name: string;
          text: string;
          completed: boolean;
        }> => {
          let text = "";
          for await (const event of parseSse(stream)) {
            if (event["type"] === "response.output_text.delta") {
              text += String(event["delta"] ?? "");
            }
            if (event["type"] === "response.output_item.done") {
              const item = event["item"] as Record<string, unknown> | undefined;
              if (item?.["status"] === "action_required") {
                return {
                  callId: String(item["call_id"]),
                  name: String(item["name"]),
                  text,
                  completed: false,
                };
              }
            }
            if (event["type"] === "response.completed") {
              return { callId: "", name: "", text, completed: true };
            }
          }
          return { callId: "", name: "", text, completed: false };
        };

        const first = await openStream();
        expect(
          await post({
            type: "message",
            data: {
              role: "user",
              content: [
                { type: "input_text", text: "Run the two-step spike plan" },
              ],
            },
            tools: spikeTools.map((item) => ({
              type: "function",
              function: {
                name: item.name,
                description: item.description,
                parameters: item.inputSchema,
              },
            })),
          }),
        ).toBe(202);

        const callOne = await readUntilCall(first);
        expect(callOne.name).toBe("get_test_nonce");
        expect(callOne.callId).not.toBe("");

        // The public segment is now closed while the provider run stays parked.
        // Wait past Omnigent's heartbeat so an idle-timeout teardown would show.
        await delay(20_000);

        const parked = await snapshot();
        const pending = parked["pending_elicitations"];
        const items = parked["items"];

        // Reattach before answering, so the second call is published to a live
        // subscriber. The replay gap is a separate, known property.
        const second = await openStream();
        expect(
          await post({
            type: "function_call_output",
            data: {
              call_id: callOne.callId,
              output: JSON.stringify({ nonce: "spike-nonce-1" }),
            },
          }),
        ).toBe(202);

        const callTwo = await readUntilCall(second);
        let duplicateStatus = 0;
        let finalText = "";
        let completed = false;
        if (callTwo.callId !== "") {
          // Same output twice for one call: the second must not double-apply.
          duplicateStatus = await post({
            type: "function_call_output",
            data: {
              call_id: callOne.callId,
              output: JSON.stringify({ nonce: "spike-nonce-1" }),
            },
          });
          const third = await openStream();
          expect(
            await post({
              type: "function_call_output",
              data: {
                call_id: callTwo.callId,
                output: JSON.stringify({ acknowledged: true }),
              },
            }),
          ).toBe(202);
          const tail = await readUntilCall(third);
          finalText = tail.text;
          completed = tail.completed;
        }

        return {
          providerSessionId,
          callOneId: callOne.callId,
          callTwoId: callTwo.callId,
          callTwoName: callTwo.name,
          duplicateStatus,
          finalText,
          completed,
          parkedStatus: parked["status"],
          parkedRunnerOnline: parked["runner_online"],
          pendingCount: Array.isArray(pending) ? pending.length : -1,
          itemCount: Array.isArray(items) ? items.length : -1,
          activeResponseId: parked["active_response_id"],
          pending,
          pendingInputs: parked["pending_inputs"],
          snapshotItems: items,
        };
      },
      {
        extraEnv: {
          AGENT_CONNECT_DETERMINISTIC_PLAN: JSON.stringify([
            { name: "get_test_nonce", arguments: {} },
            { name: "confirm_test_nonce", arguments: {} },
          ]),
        },
      },
    );

    const observed = result.value;
    process.stdout.write(`\n[spike] ${JSON.stringify(observed, null, 2)}\n\n`);

    // Property 1: the run survives the deliberate mid-run stream detach.
    expect(observed.parkedRunnerOnline).toBe(true);
    expect(observed.parkedStatus).not.toBe("failed");

    // Property 2 (NEGATIVE, and the load-bearing finding): while an
    // application call is parked, Omnigent's snapshot does not report it.
    // `pending_elicitations` covers approval prompts, not application MCP
    // tool calls; the call is an in-flight `tools/call` inside the runner and
    // never becomes a committed conversation item. The gateway therefore
    // cannot use the provider snapshot to recover unresolved calls, and its
    // own persist-before-publication record is the only source of truth for
    // them. Asserted so the day Omnigent starts reporting it, this fails and
    // we revisit.
    expect(observed.pendingCount).toBe(0);
    expect(observed.pendingInputs).toEqual([]);
    expect(observed.activeResponseId).toBeNull();
    expect(
      (observed.snapshotItems as Array<Record<string, unknown>>).map(
        (item) => item["type"],
      ),
    ).not.toContain("function_call");

    // Property 3: a second sequential call arrives on the same retained run.
    expect(observed.callTwoName).toBe("confirm_test_nonce");
    expect(observed.callTwoId).not.toBe("");
    expect(observed.callTwoId).not.toBe(observed.callOneId);

    // Property 4: a repeated output for a resolved call is accepted as a no-op.
    expect(observed.duplicateStatus).toBe(202);

    // Property 5: the run reaches its own completion after both calls.
    expect(observed.completed).toBe(true);

    // Property 6: every output was submitted on a different HTTP connection
    // from the one that delivered its call, and each was accepted. The private
    // call ID is therefore not bound to the connection that observed it, which
    // is what a gateway restart needs in order to redrive a persisted output.
    expect(observed.finalText).toContain("spike-nonce-1");
    expect(observed.finalText).toContain("acknowledged");
  }, 240_000);
});

interface HarnessContext {
  readonly root: string;
  readonly serverUrl: string;
  readonly serverPort: number;
  readonly workspace: string;
  readonly transcript: string;
  readonly env: NodeJS.ProcessEnv;
  readonly processGroupIds: readonly number[];
  readonly activePids: () => number[];
  readonly serviceOutput: () => string;
  readonly operatorCanaryBefore: Record<string, string>;
}

interface HarnessResult<T> {
  readonly value: T;
  readonly root: string;
  readonly serverPort: number;
  readonly processGroupIds: readonly number[];
  readonly operatorCanaryBefore: Record<string, string>;
  readonly operatorCanaryAfter: Record<string, string>;
}

async function withIsolatedOmnigent<T>(
  operation: (context: HarnessContext) => Promise<T>,
  options: { readonly extraEnv?: NodeJS.ProcessEnv } = {},
): Promise<HarnessResult<T>> {
  const root = mkdtempSync(join(tmpdir(), "agent-connect-omnigent-"));
  const home = join(root, "home");
  const configHome = join(root, "config-home");
  const dataDir = join(root, "data");
  const cacheDir = join(root, "cache");
  const xdgConfig = join(root, "xdg-config");
  const xdgData = join(root, "xdg-data");
  const workspace = join(root, "workspace");
  const codexHome = join(root, "empty-codex-home");
  const tempDir = join(root, "tmp");
  const uvCache = join(root, "uv-cache");
  const transcript = join(root, "acp-transcript.jsonl");
  for (const directory of [
    home,
    configHome,
    dataDir,
    cacheDir,
    xdgConfig,
    xdgData,
    workspace,
    codexHome,
    tempDir,
    uvCache,
  ]) {
    mkdirSync(directory, { recursive: true, mode: 0o700 });
  }

  const operatorCanaryBefore = snapshotOperatorCanaries();
  const env: NodeJS.ProcessEnv = {
    PATH: process.env.PATH,
    LANG: process.env.LANG ?? "C.UTF-8",
    LC_ALL: process.env.LC_ALL,
    USER: process.env.USER,
    LOGNAME: process.env.LOGNAME,
    SHELL: process.env.SHELL,
    HOME: home,
    CODEX_HOME: codexHome,
    TMPDIR: tempDir,
    XDG_CACHE_HOME: cacheDir,
    XDG_CONFIG_HOME: xdgConfig,
    XDG_DATA_HOME: xdgData,
    UV_CACHE_DIR: uvCache,
    OMNIGENT_CONFIG_HOME: configHome,
    OMNIGENT_DATA_DIR: dataDir,
    OMNIGENT_RUNNER_ENV_PASSTHROUGH:
      "AGENT_CONNECT_ACP_TRANSCRIPT,AGENT_CONNECT_DETERMINISTIC_PLAN,CODEX_HOME,HOME,PATH,TMPDIR,UV_CACHE_DIR,XDG_CACHE_HOME,XDG_CONFIG_HOME,XDG_DATA_HOME",
    AGENT_CONNECT_ACP_TRANSCRIPT: transcript,
    NO_BROWSER: "1",
    NO_PROXY: "127.0.0.1,localhost",
    no_proxy: "127.0.0.1,localhost",
    ...options.extraEnv,
  };

  const versionOutput = execFileSync("omnigent", ["--version"], {
    env,
    encoding: "utf8",
  }).trim();
  const version = /omnigent\s+(\S+)/.exec(versionOutput)?.[1];
  if (version !== compat.version) {
    rmSync(root, { recursive: true, force: true });
    throw new Error(
      `Omnigent integration requires ${compat.version}; observed ${version ?? versionOutput}`,
    );
  }
  process.stdout.write(
    `Omnigent integration compatibility accepted: ${version}\n`,
  );

  const agentScript = join(
    repositoryRoot,
    "scripts/deterministic-acp-agent.mjs",
  );
  const configPath = join(configHome, "config.yaml");
  writeFileSync(
    configPath,
    `telemetry: false\n\nacp:\n  agents:\n    - name: Codex ACP\n      command: ${JSON.stringify(`${process.execPath} ${agentScript}`)}\n      session_id_mode: server\n`,
    { mode: 0o600 },
  );

  const serverPort = await freePort();
  const serverUrl = `http://127.0.0.1:${serverPort}`;
  const processes: LoggedProcess[] = [];
  let value!: T;
  let operationError: unknown;
  let cleanupError: unknown;
  try {
    const server = spawnLogged(
      "omnigent-server",
      "omnigent",
      [
        "server",
        "--host",
        "127.0.0.1",
        "--port",
        String(serverPort),
        "--config",
        configPath,
        "--no-open",
      ],
      env,
    );
    processes.push(server);
    await waitFor(
      "Omnigent server",
      async () => {
        const response = await fetch(`${serverUrl}/v1/hosts`).catch(
          () => undefined,
        );
        return response?.ok === true;
      },
      server,
    );

    const host = spawnLogged(
      "omnigent-host",
      "omnigent",
      ["host", "--server", serverUrl, "--non-interactive"],
      env,
    );
    processes.push(host);
    await waitFor(
      "online Omnigent host",
      async () => {
        const response = await fetch(`${serverUrl}/v1/hosts`).catch(
          () => undefined,
        );
        if (!response?.ok) return false;
        const body = (await response.json()) as {
          hosts?: Array<{ status?: string }>;
        };
        return body.hosts?.some((item) => item.status === "online") === true;
      },
      host,
    );

    value = await operation({
      root,
      serverUrl,
      serverPort,
      workspace,
      transcript,
      env,
      processGroupIds: processes.flatMap((item) =>
        item.child.pid ? [item.child.pid] : [],
      ),
      activePids: () => findProcessesReferencing(root),
      serviceOutput: () => processes.map((item) => item.output()).join("\n"),
      operatorCanaryBefore,
    });
  } catch (error) {
    operationError = error;
  } finally {
    try {
      for (const process of processes.reverse())
        await stopProcess(process.child);
      await waitUntilPortClosed(serverPort);
      await stopProcessesReferencing(root);
      const remainingPids = findProcessesReferencing(root);
      if (remainingPids.length > 0) {
        throw new Error(
          `Omnigent cleanup left processes referencing the isolated root: ${remainingPids.join(", ")}`,
        );
      }
    } catch (error) {
      cleanupError = error;
    }
  }

  let operatorCanaryAfter: Record<string, string> = {};
  try {
    operatorCanaryAfter = snapshotOperatorCanaries();
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
  if (operationError !== undefined && cleanupError !== undefined) {
    throw new AggregateError(
      [operationError, cleanupError],
      "Omnigent operation and cleanup both failed",
    );
  }
  if (operationError !== undefined) throw operationError;
  if (cleanupError !== undefined) throw cleanupError;
  return {
    value,
    root,
    serverPort,
    processGroupIds: processes.flatMap((item) =>
      item.child.pid ? [item.child.pid] : [],
    ),
    operatorCanaryBefore,
    operatorCanaryAfter,
  };
}

// Milestone 2, step 5 of docs/plan/open-responses-vertical-slice.md: two
// sequential application calls driven entirely through `previous_response_id`,
// against real Omnigent, with one retained provider session underneath.
integration("Open Responses through the gateway", () => {
  const responseTools = [
    {
      name: "get_test_nonce",
      description: "Return an unpredictable nonce generated by the application",
      inputSchema: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
    {
      name: "confirm_test_nonce",
      description: "Acknowledge a nonce previously produced by the application",
      inputSchema: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  ];

  it("completes two sequential calls over POST /v1/responses", async () => {
    const result = await withIsolatedOmnigent(
      async (harness) => {
        assertIsolatedEnvironment(harness);
        const omnigent = new OmnigentRuntime({
          baseUrl: harness.serverUrl,
          workspace: harness.workspace,
          launchTimeoutMs: 30_000,
          pollIntervalMs: 100,
        });
        // Counts provisioning directly: the point of the design is that three
        // public response segments run on one provider session.
        const providerSessionIds: string[] = [];
        const runtime = {
          createSession: async (request: RuntimeSessionRequest) => {
            const id = await omnigent.createSession(request);
            providerSessionIds.push(id);
            return id;
          },
          isHealthy: (id: string) => omnigent.isHealthy(id),
        };
        const gateway = createGateway({
          allowedOrigins: new Set(["https://integration.example"]),
          allowedTailscaleUsers: new Set(["owner@example.com"]),
          omnigentBaseUrl: harness.serverUrl,
          runtime,
          authStatePath: join(harness.root, "gateway-responses-auth.json"),
          responseStatePath: join(harness.root, "gateway-responses"),
          publicEndpoint: "https://integration-runtime.example",
          enrollmentPassphrase: "integration enrollment phrase",
        });
        liveGateways.push(gateway);
        await new Promise<void>((resolve) =>
          gateway.listen(0, "127.0.0.1", resolve),
        );
        const gatewayUrl = `http://127.0.0.1:${(gateway.address() as AddressInfo).port}`;
        const capability = await authorizeApplication(
          gatewayUrl,
          responseTools,
        );

        const wireTools = responseTools.map((item) => ({
          type: "function",
          name: item.name,
          description: item.description,
          parameters: item.inputSchema,
        }));
        const createResponse = async (
          body: Record<string, unknown>,
        ): Promise<Record<string, unknown>[]> => {
          const response = await fetch(`${gatewayUrl}/v1/responses`, {
            method: "POST",
            headers: {
              Origin: "https://integration.example",
              "Tailscale-User-Login": "owner@example.com",
              Authorization: `Bearer ${capability}`,
              "Content-Type": "application/json",
              Accept: "text/event-stream",
            },
            body: JSON.stringify({ ...body, model: "agent-connect/default" }),
          });
          expect(response.status).toBe(200);
          expect(response.body).not.toBeNull();
          const events: Record<string, unknown>[] = [];
          for await (const event of parseSse(response.body!)) {
            events.push(event);
            if (
              event["type"] === "response.completed" ||
              event["type"] === "response.failed" ||
              event["type"] === "response.incomplete"
            ) {
              break;
            }
          }
          return events;
        };

        const first = await createResponse({
          stream: true,
          input: "Run the two-step spike plan",
          tools: wireTools,
        });
        const firstCall = functionCallOf(first);
        const nonce = `app-${randomUUID()}`;

        const second = await createResponse({
          stream: true,
          previous_response_id: responseIdOf(first),
          input: [
            {
              type: "function_call_output",
              call_id: firstCall["call_id"],
              output: JSON.stringify({ nonce }),
            },
          ],
        });
        const secondCall = functionCallOf(second);

        const third = await createResponse({
          stream: true,
          previous_response_id: responseIdOf(second),
          input: [
            {
              type: "function_call_output",
              call_id: secondCall["call_id"],
              output: JSON.stringify({ acknowledged: true }),
            },
          ],
        });

        return {
          nonce,
          firstCallId: String(firstCall["call_id"]),
          firstCallName: String(firstCall["name"]),
          secondCallId: String(secondCall["call_id"]),
          secondCallName: String(secondCall["name"]),
          finalStatus: String(
            (third.at(-1)?.["response"] as Record<string, unknown>)?.["status"],
          ),
          finalTypes: third.map((event) => String(event["type"])),
          allTypes: [...first, ...second, ...third].map((event) =>
            String(event["type"]),
          ),
          rendered: JSON.stringify([...first, ...second, ...third]),
          providerSessionIds,
        };
      },
      {
        extraEnv: {
          AGENT_CONNECT_DETERMINISTIC_PLAN: JSON.stringify([
            { name: "get_test_nonce", arguments: {} },
            { name: "confirm_test_nonce", arguments: {} },
          ]),
        },
      },
    );

    const observed = result.value;
    process.stdout.write(
      `\n[responses] ${JSON.stringify(
        { ...observed, rendered: undefined },
        null,
        2,
      )}\n\n`,
    );

    expect(observed.firstCallName).toBe("get_test_nonce");
    expect(observed.secondCallName).toBe("confirm_test_nonce");
    expect(observed.secondCallId).not.toBe(observed.firstCallId);
    expect(observed.finalStatus).toBe("completed");
    expect(observed.finalTypes.at(-1)).toBe("response.completed");
    // One Omnigent session served all three public response segments.
    expect(observed.providerSessionIds).toHaveLength(1);
    // Nothing Omnigent-shaped reaches the client: no `action_required`, no
    // provider session id, no ACP event, no provider request token.
    expect(observed.rendered).not.toContain("action_required");
    expect(observed.rendered).not.toContain("session.");
    expect(
      observed.allTypes.every((type) => type.startsWith("response.")),
    ).toBe(true);
  }, 240_000);

  it("cancels a chain parked on an unanswered call", async () => {
    const result = await withIsolatedOmnigent(
      async (harness) => {
        assertIsolatedEnvironment(harness);
        const omnigent = new OmnigentRuntime({
          baseUrl: harness.serverUrl,
          workspace: harness.workspace,
          launchTimeoutMs: 30_000,
          pollIntervalMs: 100,
        });
        const providerSessionIds: string[] = [];
        const runtime = {
          createSession: async (request: RuntimeSessionRequest) => {
            const id = await omnigent.createSession(request);
            providerSessionIds.push(id);
            return id;
          },
          isHealthy: (id: string) => omnigent.isHealthy(id),
        };
        const gateway = createGateway({
          allowedOrigins: new Set(["https://integration.example"]),
          allowedTailscaleUsers: new Set(["owner@example.com"]),
          omnigentBaseUrl: harness.serverUrl,
          runtime,
          authStatePath: join(harness.root, "gateway-cancel-auth.json"),
          responseStatePath: join(harness.root, "gateway-cancel"),
          publicEndpoint: "https://integration-runtime.example",
          enrollmentPassphrase: "integration enrollment phrase",
        });
        liveGateways.push(gateway);
        await new Promise<void>((resolve) =>
          gateway.listen(0, "127.0.0.1", resolve),
        );
        const gatewayUrl = `http://127.0.0.1:${(gateway.address() as AddressInfo).port}`;
        const capability = await authorizeApplication(
          gatewayUrl,
          responseTools,
        );
        const headers = {
          Origin: "https://integration.example",
          "Tailscale-User-Login": "owner@example.com",
          Authorization: `Bearer ${capability}`,
        };

        const created = await fetch(`${gatewayUrl}/v1/responses`, {
          method: "POST",
          headers: { ...headers, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: "agent-connect/default",
            stream: true,
            input: "Run the two-step spike plan",
            tools: responseTools.map((item) => ({
              type: "function",
              name: item.name,
              description: item.description,
              parameters: item.inputSchema,
            })),
          }),
        });
        expect(created.status).toBe(200);
        const events: Record<string, unknown>[] = [];
        for await (const event of parseSse(created.body!)) {
          events.push(event);
          if (event["type"] === "response.completed") break;
        }
        const parkedCall = functionCallOf(events);
        const responseId = responseIdOf(events);

        // The chain is now parked on an unanswered application call, which is
        // the state a client cancels from.
        const cancelled = await fetch(
          `${gatewayUrl}/v1/agent-connect/responses/${responseId}/cancel`,
          { method: "POST", headers },
        );
        expect(cancelled.status).toBe(200);
        const cancelledBody = (await cancelled.json()) as {
          chain_status: string;
        };

        // Evidence that the cancellation reached the run, not only the
        // gateway's own record of it.
        const providerSessionId = providerSessionIds[0] ?? "";
        let providerStatus = "";
        const deadline = Date.now() + 30_000;
        while (Date.now() < deadline) {
          const snapshot = await fetch(
            `${harness.serverUrl}/v1/sessions/${encodeURIComponent(providerSessionId)}`,
            { headers: { Origin: "omnigent://internal" } },
          );
          providerStatus = String(
            ((await snapshot.json()) as Record<string, unknown>)["status"],
          );
          if (providerStatus !== "running") break;
          await delay(500);
        }

        const afterCancel = await fetch(`${gatewayUrl}/v1/responses`, {
          method: "POST",
          headers: { ...headers, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: "agent-connect/default",
            previous_response_id: responseId,
            input: [
              {
                type: "function_call_output",
                call_id: parkedCall["call_id"],
                output: "{}",
              },
            ],
          }),
        });
        const afterCancelBody = (await afterCancel.json()) as {
          error: { code: string };
        };

        return {
          chainStatus: cancelledBody.chain_status,
          providerStatus,
          continueStatus: afterCancel.status,
          continueCode: afterCancelBody.error.code,
        };
      },
      {
        extraEnv: {
          AGENT_CONNECT_DETERMINISTIC_PLAN: JSON.stringify([
            { name: "get_test_nonce", arguments: {} },
            { name: "confirm_test_nonce", arguments: {} },
          ]),
        },
      },
    );

    const observed = result.value;
    process.stdout.write(
      `\n[responses-cancel] ${JSON.stringify(observed, null, 2)}\n\n`,
    );
    expect(observed.chainStatus).toBe("terminal");
    // The parked Omnigent run stopped running rather than waiting forever.
    expect(observed.providerStatus).not.toBe("running");
    expect(observed.continueStatus).toBe(409);
    expect(observed.continueCode).toBe("response_cancelled");
  }, 240_000);
});

/** The full authorization ceremony, returning a session capability. */
async function authorizeApplication(
  gatewayUrl: string,
  tools: readonly {
    readonly name: string;
    readonly description: string;
    readonly inputSchema: Record<string, unknown>;
  }[],
): Promise<string> {
  const headers = {
    Origin: "https://integration.example",
    "Tailscale-User-Login": "owner@example.com",
  };
  const verifier = "v".repeat(43);
  const pushed = await fetch(`${gatewayUrl}/v1/authorization-requests`, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({
      appId: "integration-test",
      redirectUri: "https://integration.example/oauth/callback",
      state: "integration_state",
      codeChallenge: createHash("sha256").update(verifier).digest("base64url"),
      scopes: ["agent:prompt", "agent:result", "tools:invoke"],
      tools,
    }),
  });
  expect(pushed.status).toBe(201);
  const { requestId } = (await pushed.json()) as { requestId: string };
  const approval = await fetch(`${gatewayUrl}/authorize`, {
    method: "POST",
    redirect: "manual",
    headers: {
      "Tailscale-User-Login": "owner@example.com",
      Origin: "https://integration-runtime.example",
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      request: requestId,
      decision: "approve",
      passphrase: "integration enrollment phrase",
    }),
  });
  expect(approval.status).toBe(303);
  const code =
    new URL(approval.headers.get("location") ?? "").searchParams.get("code") ??
    "";
  const token = await fetch(`${gatewayUrl}/oauth/token`, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({
      code,
      codeVerifier: verifier,
      appId: "integration-test",
      redirectUri: "https://integration.example/oauth/callback",
    }),
  });
  expect(token.status).toBe(200);
  const grant = (await token.json()) as { accessToken: string };
  const session = await fetch(`${gatewayUrl}/v1/app-sessions`, {
    method: "POST",
    headers: {
      ...headers,
      Authorization: `Bearer ${grant.accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ appId: "integration-test", tools }),
  });
  expect(session.status).toBe(201);
  return ((await session.json()) as { accessToken: string }).accessToken;
}

function responseIdOf(events: readonly Record<string, unknown>[]): string {
  const created = events.find((event) => event["type"] === "response.created");
  const response = created?.["response"] as Record<string, unknown> | undefined;
  return String(response?.["id"]);
}

function functionCallOf(
  events: readonly Record<string, unknown>[],
): Record<string, unknown> {
  const done = events.filter(
    (event) => event["type"] === "response.output_item.done",
  );
  const item = done
    .map((event) => event["item"] as Record<string, unknown>)
    .find((candidate) => candidate?.["type"] === "function_call");
  if (!item) throw new Error("the segment produced no function call");
  return item;
}

async function exerciseToolLoop(
  harness: HarnessContext,
  options: { readonly onActionRequired?: () => void } = {},
): Promise<{
  nonce: string;
  text: string;
  completed: boolean;
  transcript: Array<Record<string, unknown>>;
}> {
  assertIsolatedEnvironment(harness);
  const runtime = new OmnigentRuntime({
    baseUrl: harness.serverUrl,
    workspace: harness.workspace,
    launchTimeoutMs: 30_000,
    pollIntervalMs: 100,
  });
  const gateway = createGateway({
    allowedOrigins: new Set(["https://integration.example"]),
    allowedTailscaleUsers: new Set(["owner@example.com"]),
    omnigentBaseUrl: harness.serverUrl,
    runtime,
    authStatePath: join(harness.root, "gateway-auth.json"),
    publicEndpoint: "https://integration-runtime.example",
    enrollmentPassphrase: "integration enrollment phrase",
  });
  liveGateways.push(gateway);
  await new Promise<void>((resolve) => gateway.listen(0, "127.0.0.1", resolve));
  const gatewayAddress = gateway.address() as AddressInfo;
  const gatewayUrl = `http://127.0.0.1:${gatewayAddress.port}`;
  const headers = {
    Origin: "https://integration.example",
    "Tailscale-User-Login": "owner@example.com",
  };
  const tool = {
    name: "get_test_nonce",
    description: "Return an unpredictable nonce generated by the application",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  };
  const verifier = "v".repeat(43);
  const codeChallenge = createHash("sha256")
    .update(verifier)
    .digest("base64url");
  const authorizationResponse = await fetch(
    `${gatewayUrl}/v1/authorization-requests`,
    {
      method: "POST",
      headers: { ...headers, "Content-Type": "application/json" },
      body: JSON.stringify({
        appId: "integration-test",
        redirectUri: "https://integration.example/oauth/callback",
        state: "integration_state",
        codeChallenge,
        scopes: ["agent:prompt", "agent:result", "tools:invoke"],
        tools: [tool],
      }),
    },
  );
  expect(authorizationResponse.status).toBe(201);
  const authorization = (await authorizationResponse.json()) as {
    requestId: string;
  };
  const approvalResponse = await fetch(`${gatewayUrl}/authorize`, {
    method: "POST",
    redirect: "manual",
    headers: {
      "Tailscale-User-Login": "owner@example.com",
      Origin: "https://integration-runtime.example",
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      request: authorization.requestId,
      decision: "approve",
      passphrase: "integration enrollment phrase",
    }),
  });
  expect(approvalResponse.status).toBe(303);
  const code = new URL(
    approvalResponse.headers.get("location") ?? "",
  ).searchParams.get("code");
  expect(code).toMatch(/^acc_/);
  const tokenResponse = await fetch(`${gatewayUrl}/oauth/token`, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({
      code,
      codeVerifier: verifier,
      appId: "integration-test",
      redirectUri: "https://integration.example/oauth/callback",
    }),
  });
  expect(tokenResponse.status).toBe(200);
  const grant = (await tokenResponse.json()) as { accessToken: string };
  const createdResponse = await fetch(`${gatewayUrl}/v1/app-sessions`, {
    method: "POST",
    headers: {
      ...headers,
      Authorization: `Bearer ${grant.accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ appId: "integration-test", tools: [tool] }),
  });
  expect(createdResponse.status).toBe(201);
  const created = (await createdResponse.json()) as {
    sessionId: string;
    accessToken: string;
  };

  const sessionUrl = `${gatewayUrl}/v1/sessions/${created.sessionId}`;
  const streamResponse = await fetch(`${sessionUrl}/stream`, {
    headers: {
      ...headers,
      Authorization: `Bearer ${created.accessToken}`,
      Accept: "text/event-stream",
    },
  });
  expect(streamResponse.status).toBe(200);
  expect(streamResponse.body).not.toBeNull();

  const postMessage = await fetch(`${sessionUrl}/events`, {
    method: "POST",
    headers: {
      ...headers,
      Authorization: `Bearer ${created.accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      type: "message",
      data: {
        role: "user",
        content: [{ type: "input_text", text: "Call get_test_nonce once" }],
      },
      tools: [
        {
          type: "function",
          function: {
            name: tool.name,
            description: tool.description,
            parameters: tool.inputSchema,
          },
        },
      ],
    }),
  });
  expect(postMessage.status).toBe(202);

  let nonce = "";
  let text = "";
  let completed = false;
  for await (const event of parseSse(streamResponse.body!)) {
    if (event["type"] === "response.output_text.delta") {
      text += String(event["delta"] ?? "");
    }
    if (event["type"] === "response.output_item.done") {
      const item = event["item"] as Record<string, unknown> | undefined;
      if (item?.["status"] === "action_required") {
        expect(item["name"]).toBe("get_test_nonce");
        expect(parseArguments(item["arguments"])).toEqual({});
        expect(nonce).toBe("");
        options.onActionRequired?.();
        nonce = `app-${randomUUID()}`;
        const toolResult = await fetch(`${sessionUrl}/events`, {
          method: "POST",
          headers: {
            ...headers,
            Authorization: `Bearer ${created.accessToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            type: "function_call_output",
            data: {
              call_id: item["call_id"],
              output: JSON.stringify({ nonce }),
            },
          }),
        });
        expect(toolResult.status).toBe(202);
      }
    }
    if (event["type"] === "response.completed") {
      completed = true;
      break;
    }
  }

  expect(nonce).not.toBe("");
  expect(text).toContain(nonce);
  expect(existsSync(join(harness.root, "data/chat.db"))).toBe(true);
  expect(existsSync(join(harness.root, "data/artifacts"))).toBe(true);
  expect(existsSync(harness.transcript)).toBe(true);
  expect(existsSync(join(harness.root, "home/.omnigent/logs"))).toBe(true);
  expect(
    existsSync(join(harness.root, "home/.omnigent/logs/host-runner")),
  ).toBe(true);
  expect(existsSync(join(harness.root, "empty-codex-home/auth.json"))).toBe(
    false,
  );
  expect(harness.activePids().length).toBeGreaterThanOrEqual(4);
  const operatorHome = process.env.HOME ?? "";
  expect(harness.serviceOutput()).not.toContain(
    join(operatorHome, ".omnigent"),
  );
  expect(harness.serviceOutput()).not.toContain(join(operatorHome, ".codex"));
  const isolatedFiles = listFiles(harness.root).map((path) =>
    relative(harness.root, path),
  );
  expect(isolatedFiles).toEqual(
    expect.arrayContaining(["data/chat.db", "acp-transcript.jsonl"]),
  );
  expect(
    isolatedFiles.some((path) =>
      path.startsWith("home/.omnigent/logs/host-runner/runner-"),
    ),
  ).toBe(true);
  const transcript = readFileSync(harness.transcript, "utf8")
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Record<string, unknown>);
  return { nonce, text, completed, transcript };
}

function assertIsolatedEnvironment(harness: HarnessContext): void {
  for (const name of [
    "HOME",
    "CODEX_HOME",
    "TMPDIR",
    "UV_CACHE_DIR",
    "XDG_CACHE_HOME",
    "XDG_CONFIG_HOME",
    "XDG_DATA_HOME",
    "OMNIGENT_CONFIG_HOME",
    "OMNIGENT_DATA_DIR",
    "AGENT_CONNECT_ACP_TRANSCRIPT",
  ]) {
    const value = harness.env[name];
    expect(value, `${name} must be set`).toBeTruthy();
    expect(isWithin(harness.root, value!)).toBe(true);
  }
  expect(isWithin(harness.root, harness.workspace)).toBe(true);
  const credentialKeys = Object.keys(harness.env).filter((name) =>
    /(?:OPENAI|ANTHROPIC|GEMINI|API_KEY|ACCESS_TOKEN|AUTH_TOKEN|CREDENTIAL)/i.test(
      name,
    ),
  );
  expect(credentialKeys).toEqual([]);
}

function snapshotOperatorCanaries(): Record<string, string> {
  const home = process.env.HOME ?? "";
  const paths = [
    join(home, ".omnigent/config.yaml"),
    join(home, ".omnigent/logs"),
    join(home, ".codex/auth.json"),
  ];
  return Object.fromEntries(
    paths.map((path) => {
      if (!existsSync(path)) return [path, "missing"];
      return [
        path,
        createHash("sha256").update(snapshotMetadata(path)).digest("hex"),
      ];
    }),
  );
}

function snapshotMetadata(path: string): string {
  const root = resolve(path);
  const entries: Array<Record<string, unknown>> = [];
  const visit = (current: string) => {
    const stat = statSync(current);
    entries.push({
      path: relative(root, current) || ".",
      type: stat.isDirectory() ? "directory" : "file",
      size: stat.size,
      mode: stat.mode,
      mtimeMs: stat.mtimeMs,
    });
    if (!stat.isDirectory()) return;
    for (const entry of readdirSync(current).sort()) {
      visit(join(current, entry));
    }
  };
  visit(root);
  return JSON.stringify(entries);
}

interface LoggedProcess {
  readonly child: ChildProcess;
  readonly output: () => string;
}

function spawnLogged(
  name: string,
  command: string,
  args: string[],
  env: NodeJS.ProcessEnv,
): LoggedProcess {
  const child = spawn(command, args, {
    env,
    detached: true,
    stdio: ["ignore", "pipe", "pipe"],
  });
  let output = "";
  const collect = (chunk: Buffer) => {
    output = `${output}${chunk.toString("utf8")}`.slice(-16_000);
  };
  child.stdout?.on("data", collect);
  child.stderr?.on("data", collect);
  child.on("error", (error) =>
    collect(Buffer.from(`${name}: ${error.message}`)),
  );
  return { child, output: () => output };
}

async function waitFor(
  description: string,
  check: () => Promise<boolean>,
  process: LoggedProcess,
  timeoutMs = 30_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (process.child.exitCode !== null) {
      throw new Error(
        `${description} process exited (${process.child.exitCode})\n${process.output()}`,
      );
    }
    if (await check()) return;
    await delay(200);
  }
  throw new Error(`Timed out waiting for ${description}\n${process.output()}`);
}

async function stopProcess(child: ChildProcess): Promise<void> {
  if (!child.pid) return;
  const processGroupId = child.pid;
  try {
    process.kill(-processGroupId, "SIGTERM");
  } catch {
    if (child.exitCode === null) child.kill("SIGTERM");
  }
  await waitForExit(child, 5_000);
  if (!(await waitForProcessGroupExit(processGroupId, 5_000))) {
    try {
      process.kill(-processGroupId, "SIGKILL");
    } catch {
      if (child.exitCode === null) child.kill("SIGKILL");
    }
  }
  if (!(await waitForProcessGroupExit(processGroupId, 5_000))) {
    throw new Error(`Process group ${processGroupId} survived cleanup`);
  }
}

async function waitForProcessGroupExit(
  processGroupId: number,
  timeoutMs: number,
): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (!processGroupExists(processGroupId)) return true;
    await delay(100);
  }
  return !processGroupExists(processGroupId);
}

function processGroupExists(processGroupId: number): boolean {
  try {
    process.kill(-processGroupId, 0);
    return true;
  } catch (error) {
    return !(
      error instanceof Error &&
      "code" in error &&
      (error as NodeJS.ErrnoException).code === "ESRCH"
    );
  }
}

function waitForExit(child: ChildProcess, timeoutMs: number): Promise<boolean> {
  if (child.exitCode !== null) return Promise.resolve(true);
  return new Promise((resolve) => {
    const timeout = setTimeout(() => {
      child.off("exit", onExit);
      resolve(false);
    }, timeoutMs);
    const onExit = () => {
      clearTimeout(timeout);
      resolve(true);
    };
    child.once("exit", onExit);
  });
}

function findProcessesReferencing(marker: string): number[] {
  const result: number[] = [];
  for (const entry of readdirSync("/proc")) {
    if (!/^\d+$/.test(entry)) continue;
    try {
      const environment = readFileSync(`/proc/${entry}/environ`);
      if (environment.includes(Buffer.from(marker))) result.push(Number(entry));
    } catch {
      // Processes may exit or be inaccessible while /proc is scanned.
    }
  }
  return result.sort((left, right) => left - right);
}

async function stopProcessesReferencing(marker: string): Promise<void> {
  for (const pid of findProcessesReferencing(marker)) {
    try {
      process.kill(pid, "SIGTERM");
    } catch {
      // It may have exited between the /proc scan and the signal.
    }
  }
  const deadline = Date.now() + 5_000;
  while (Date.now() < deadline) {
    if (findProcessesReferencing(marker).length === 0) return;
    await delay(100);
  }
  for (const pid of findProcessesReferencing(marker)) {
    try {
      process.kill(pid, "SIGKILL");
    } catch {
      // It may have exited between the /proc scan and the signal.
    }
  }
  await delay(100);
}

async function freePort(): Promise<number> {
  const server = createNetServer();
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const port = (server.address() as AddressInfo).port;
  await closeServer(server);
  return port;
}

async function expectPortClosed(port: number): Promise<void> {
  expect(await canConnect(port)).toBe(false);
}

async function waitUntilPortClosed(port: number): Promise<void> {
  const deadline = Date.now() + 5_000;
  while (Date.now() < deadline) {
    if (!(await canConnect(port))) return;
    await delay(100);
  }
  throw new Error(`Omnigent server port ${port} remained open after cleanup`);
}

function canConnect(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = connect({ host: "127.0.0.1", port });
    socket.once("connect", () => {
      socket.destroy();
      resolve(true);
    });
    socket.once("error", () => resolve(false));
    socket.setTimeout(500, () => {
      socket.destroy();
      resolve(false);
    });
  });
}

async function closeServer(server: {
  close(callback: (error?: Error) => void): void;
}) {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
}

async function* parseSse(
  body: ReadableStream<Uint8Array>,
): AsyncGenerator<Record<string, unknown>> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  const deadline = Date.now() + 45_000;
  try {
    while (Date.now() < deadline) {
      const read = reader.read();
      const result = await Promise.race([
        read,
        delay(45_000).then(() => {
          throw new Error("Timed out reading Omnigent SSE");
        }),
      ]);
      buffer += decoder.decode(result.value, { stream: !result.done });
      const frames = buffer.split(/\r?\n\r?\n/);
      buffer = frames.pop() ?? "";
      for (const frame of frames) {
        const data = frame
          .split(/\r?\n/)
          .filter((line) => line.startsWith("data:"))
          .map((line) => line.slice(5).trimStart())
          .join("\n");
        if (data && data !== "[DONE]") {
          yield JSON.parse(data) as Record<string, unknown>;
        }
      }
      if (result.done) return;
    }
    throw new Error("Timed out waiting for Omnigent completion");
  } finally {
    await reader.cancel().catch(() => undefined);
    reader.releaseLock();
  }
}

function parseArguments(value: unknown): unknown {
  return typeof value === "string" ? JSON.parse(value) : value;
}

function listFiles(root: string): string[] {
  const result: string[] = [];
  const visit = (directory: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      result.push(path);
      if (entry.isDirectory()) visit(path);
    }
  };
  visit(root);
  return result;
}

function isWithin(root: string, path: string): boolean {
  const normalizedRoot = `${resolve(root)}/`;
  const normalizedPath = resolve(path);
  return (
    normalizedPath === resolve(root) ||
    normalizedPath.startsWith(normalizedRoot)
  );
}

function delay(milliseconds: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}
